# Generated by Django 4.0.2 on 2022-02-26 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_date_alter_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 20, 51, 33, 991442)),
        ),
    ]
