# Generated by Django 4.0.2 on 2022-02-26 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 21, 0, 19, 647311)),
        ),
    ]
