# Generated by Django 4.0.2 on 2022-02-26 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_comment_listing_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 22, 53, 0, 784218)),
        ),
    ]
