# Generated by Django 4.0.2 on 2022-02-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_bid_user_alter_listing_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='starting_bid',
            new_name='starting_price',
        ),
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
