# Generated by Django 4.0.2 on 2022-02-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_rename_current_price_listing_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.FloatField(default=0),
        ),
    ]
