# Generated by Django 4.0.3 on 2022-03-16 13:26

from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model('auctions', 'Category')
    Category(category='------').save()
    Category(category='Home').save()
    Category(category='Sports').save()
    Category(category='Technology').save()
    Category(category='Clothes').save()


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_listing_current_bid_winner'),
    ]

    operations = [
        migrations.RunPython(create_categories),

    ]
